[INSTALLATION]

> AT FIRST EXTRACT THE DOWNLOADED FILE

> THEN OPEN THE FOLDER "SPIDEY V2 ANDROID" AND INSIDE IT U CAN SEE TWO FOLDERS 

> ADD ALL THE FILES FROM THE FIRST FOLDER TO GTA3.IMG WITH REPLACE WHICH IS NAMED "ADD TO GTA3.IMG" USING IMG TOOL AND REBUILD



> IN NEXT STEP GO TO
ANDROID/DATA/COM.ROCKSTARGAMES.GTASA/FILES/TEXDB/TXD/

AND DELETE ALL FILES PRESENT THERE

> IN THE NEXT STEP COPY/CUT THE 2ND FOLDER "com.rockstargames.gtasa" 
TO-
ANDROID/DATA/

AND REPLACE (IF UR FILE MANAGER ASKS FOR IT)

> THEN IN NEXT STEP GO TO-

ANDROID/DATA/COM.ROCKSTARGAMES.GTASA/FILES/TEXDB/TXD/

> THEN REPLACE THE WORD RENAME IN THIS THREE FILES ACCORDING TO UR GPU

"txd.RENAME.dat"
"txd.RENAME.toc"
"txd.RENAME.tmb"

WITH--

etc (IF UR GPU IS MALI)

dxt (IF UR GPU IS ADRENO)

pvr (IF UR GPU IS POWERVR)

IN CASE U DONT KNOW WHAT IS UR GPU
USE CPU-Z (A APP) TO KNOW WHAT IS UR GPU



NOTE: IN CASE UR HAVING TEGRA GPU STOP DOWNLOADING GTA SA MODS AND PLAY SOME OTHER GAMES


[ADDITIONAL INFORMATION:

GTA3.IMG PATH: 
ANDROID/DATA/COM.ROCKSTARGAMES.GTASA/FILES/TEXDB/

IN-CASE U ARE USING GTA SA LITE U CAN GET THE GTA3.IMG IN THE PATH SPECIFIED ABOVE BUT IF U R USING GTA SA FULL VERSION U WILL HAVE TO EXTRACT IT FROM
patch...........obb PRESENT IN THIS PATH - Android/obb/com.rockstargames.gtasa/

TO --
ANDROID/DATA/COM.ROCKSTARGAMES.GTASA/FILES/TEXDB/

]

